name: Flutter Lint Check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Check Flutter Code with Lints
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter Lints
        run: flutter analyze .